### ISSUE TITLE
Please replace all double types in Java client with BigDecimal type otherwise you get numbers parsed like 381.04000000000002046363078989088535308837890625

### ISSUE THREAD

**Issue by b00lean** [coinapult/public#4]

**Comment by b00lean** [comment]
No.

**Comment by b00lean** [comment]
You didn't do good work on Java implementation. I don't know why I should finish the thing.

**Comment by g-p-g** [comment]
No one is telling you that you must do it, but if you want to contribute to it then you're welcome to. Otherwise you have to wait for a fix.

**Comment by g-p-g** [comment]
This has been fixed by 209a54d1e3d1c3ad9ae5bfcf702c9111449a27d5 and 4816a1f89f728321cb02331302871960b361d8d6.
