### ISSUE TITLE
Code 404 creating WebSocket

### ISSUE THREAD

**Issue by thanksmister** [coinapult/public#6]
WebSocket connection to 'wss://stream.coinapult.com/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404 

It seems connecting to the websocket stream for Coinapult is throwing an error.

**Comment by g-p-g** [comment]
It should be on port 8123, i.e. wss://stream.coinapult.com:8123/websocket

**Comment by thanksmister** [comment]
That would be great if it was documented.  You only have wss://stream.coinapult.com/websocket listed in the API documentation.

**Comment by g-p-g** [comment]
Right, it's a documentation bug in this case. I'm assuming you saw this at https://coinapult.com/developer/api/streaming? Or is there other place which needs to be fixed?

**Comment by thanksmister** [comment]
Yes, that is the only place I have seen the stream API listed.   Without examples I couldn't verify if the endpoints were correct.   Can you please also verify if the SockJS connection is accurate (no port needed, etc).  I am unable to establish a connection using that endpoint as well.

**Comment by g-p-g** [comment]
For both cases you need port 8123, thanks for reporting it.

**Comment by thanksmister** [comment]
Ok, so we are clear on this topic.   For production I would use the following stream API endpoints:

https://stream.coinapult.com:8123/  for SockJS and wss://stream.coinapult.com:8123/websocket

For the playground I would use the following stream API endpoint for both SockJS and websocket:

playground.coinapult.com:8123

Is this correct?

**Comment by g-p-g** [comment]
Yes, that is it.

**Comment by g-p-g** [comment]
This has been fixed for playground (https://playground.coinapult.com/developer/api/streaming) and will be available at coinapult.com later today. For coinapult.com the note about replacing stream.coinapult.com by playground.coinapult.com will not be present for now.

**Comment by thanksmister** [comment]
Yeah, there is no documentation at all for using the API against playground.  Perhaps the playground site  should link to API documentation for playground API usage or at least provide proper links.   Thanks!
