### ISSUE TITLE
Duplicate transactions returned from stream API

### ISSUE THREAD

**Issue by thanksmister** [coinapult/public#7]
I am seeing each "pending" transaction returned twice in rapid sequence.  Example is below output from the SockJS connection.   Expected behavior would be to see each unique transaction only once to reduce payload.  The actual behavior is to see duplicates in the stream output.  For example,  here are two different pending transactions.  Both are returned twice in rapid sequence (check timestamp on terminal dump). 

I20150312-10:25:02.388(-3)? got tx { transaction: 
I20150312-10:25:02.388(-3)?    { timestamp: 1426166701,
I20150312-10:25:02.388(-3)?      address: 'n3iwjj9bQj61zeBSLLDgUhxA5UBERt6pyY',
I20150312-10:25:02.388(-3)?      state: 'pending',
I20150312-10:25:02.388(-3)?      meta: { note: '', to: '', customid: '' },
I20150312-10:25:02.388(-3)?      transaction_id: '54f898d231433d224ac3d407',
I20150312-10:25:02.389(-3)?      in: { expected: 0.1, currency: 'BTC', amount: 0 },
I20150312-10:25:02.389(-3)?      type: 'invoice',
I20150312-10:25:02.389(-3)?      completeTime: null,
I20150312-10:25:02.389(-3)?      out: { expected: 0.1, currency: 'BTC', amount: 0 } },
I20150312-10:25:02.389(-3)?   type: 'transaction',
I20150312-10:25:02.389(-3)?   meta: 
I20150312-10:25:02.389(-3)?    { to: 'test1@thanksmister.com',
I20150312-10:25:02.389(-3)?      blockchain: { a: 'n3iwjj9bQj61zeBSLLDgUhxA5UBERt6pyY', l: 'address' },
I20150312-10:25:02.389(-3)?      flow: '+',
I20150312-10:25:02.390(-3)?      address: 'test2@thanksmister.com' } }

I20150312-10:25:02.390(-3)? got tx { transaction: 
I20150312-10:25:02.390(-3)?    { timestamp: 1426166701,
I20150312-10:25:02.390(-3)?      address: 'n3iwjj9bQj61zeBSLLDgUhxA5UBERt6pyY',
I20150312-10:25:02.390(-3)?      state: 'pending',
I20150312-10:25:02.390(-3)?      meta: { note: '', to: '', customid: '' },
I20150312-10:25:02.390(-3)?      transaction_id: '54f898d231433d224ac3d407',
I20150312-10:25:02.391(-3)?      in: { expected: 0.1, currency: 'BTC', amount: 0 },
I20150312-10:25:02.391(-3)?      type: 'invoice',
I20150312-10:25:02.391(-3)?      completeTime: null,
I20150312-10:25:02.391(-3)?      out: { expected: 0.1, currency: 'BTC', amount: 0 } },
I20150312-10:25:02.391(-3)?   type: 'transaction',
I20150312-10:25:02.391(-3)?   meta: 
I20150312-10:25:02.391(-3)?    { to: 'test1@thanksmister.com',
I20150312-10:25:02.391(-3)?      blockchain: { a: 'n3iwjj9bQj61zeBSLLDgUhxA5UBERt6pyY', l: 'address' },
I20150312-10:25:02.392(-3)?      flow: '+',
I20150312-10:25:02.392(-3)?      address: 'test2@thanksmister.com' } }

I20150312-10:25:02.416(-3)? got tx { transaction: 
I20150312-10:25:02.416(-3)?    { timestamp: 1426166701,
I20150312-10:25:02.416(-3)?      address: 'mqxKCNDzehM1sw8rPLc3hpLF9kGj3sUtzP',
I20150312-10:25:02.416(-3)?      state: 'pending',
I20150312-10:25:02.416(-3)?      meta: { note: '', to: '', customid: '' },
I20150312-10:25:02.416(-3)?      transaction_id: '54fde0fc31433d224c009d30',
I20150312-10:25:02.416(-3)?      in: { expected: 0.1, currency: 'BTC', amount: 0 },
I20150312-10:25:02.416(-3)?      type: 'invoice',
I20150312-10:25:02.416(-3)?      completeTime: null,
I20150312-10:25:02.416(-3)?      out: { expected: 0.1, currency: 'BTC', amount: 0 } },
I20150312-10:25:02.416(-3)?   type: 'transaction',
I20150312-10:25:02.416(-3)?   meta: 
I20150312-10:25:02.417(-3)?    { to: 'test1@thanksmister.com',
I20150312-10:25:02.417(-3)?      blockchain: { a: 'mqxKCNDzehM1sw8rPLc3hpLF9kGj3sUtzP', l: 'address' },
I20150312-10:25:02.417(-3)?      flow: '+',
I20150312-10:25:02.417(-3)?      address: null } }

I20150312-10:25:02.425(-3)? got tx { transaction: 
I20150312-10:25:02.425(-3)?    { timestamp: 1426166701,
I20150312-10:25:02.425(-3)?      address: 'mqxKCNDzehM1sw8rPLc3hpLF9kGj3sUtzP',
I20150312-10:25:02.425(-3)?      state: 'pending',
I20150312-10:25:02.425(-3)?      meta: { note: '', to: '', customid: '' },
I20150312-10:25:02.425(-3)?      transaction_id: '54fde0fc31433d224c009d30',
I20150312-10:25:02.425(-3)?      in: { expected: 0.1, currency: 'BTC', amount: 0 },
I20150312-10:25:02.425(-3)?      type: 'invoice',
I20150312-10:25:02.425(-3)?      completeTime: null,
I20150312-10:25:02.426(-3)?      out: { expected: 0.1, currency: 'BTC', amount: 0 } },
I20150312-10:25:02.426(-3)?   type: 'transaction',
I20150312-10:25:02.426(-3)?   meta: 
I20150312-10:25:02.426(-3)?    { to: 'test1@thanksmister.com',
I20150312-10:25:02.426(-3)?      blockchain: { a: 'mqxKCNDzehM1sw8rPLc3hpLF9kGj3sUtzP', l: 'address' },
I20150312-10:25:02.426(-3)?      flow: '+',
I20150312-10:25:02.426(-3)?      address: null } }

**Comment by g-p-g** [comment]
There is no guarantee about delivering these a single time. It depends on many internal details, including the time you create them. Does this affect you in any way?

**Comment by thanksmister** [comment]
I think because I am always seeing the duplicates delivered at the same time it seems very redundant and innefficient.  The time between transactions returned from the stream API is long in my opinion, then when they do come they come within milliseconds of each other.  This isn't very useful and causes more data than needed if this is the behavior.    Maybe its the Playground that only shows this behavior but I would hope there was a way to space out the intervals so they come more often and not clustered together.

**Comment by g-p-g** [comment]
Can you be more specific about what you mean regarding ".. so they come more often .."? Maybe this is better discussed elsewhere, since it's about understanding when the notifications are sent.

**Comment by thanksmister** [comment]
Well if you cluster the stream results within milliseconds that is the same as coming at the exact same time.  If you allow them to be more evenly spaced then data changes would be picked up faster by the clients.   If a state of "pending" becomes "complete" its more likely to be picked up by the client if the notifications don't come within milliseconds.  

After all, the pending to complete may happen but not within that short window that notifications are clustered.  So then you wait another 15 seconds to get more clustered data.  If you evenly spaced notifications it would be just half that time, around 7 seconds before getting the next notification. 

The way it works not you get two duplicate notifications for the same transaction within 15 seconds of each other.  I say duplicate because I assume notifications are generated form some polling, but they access data in the moment the notification is generated so data changes in the database wouldn't be picked up unless you space out notifications.  

Of course I am assuming how notifications might be working.  It could be that you hit the database every 7 seconds but only send out notifications every 15 and the changes would be in the notifications, one saying pending, the second saying complete for example.   However this would still be better if notifications were not clustered. 

If you want to discuss it further you can just contact me using my Github account email or ask Robinson at Coinapult for my information.

**Comment by g-p-g** [comment]
We don't cluster them within milliseconds, it just happens to be what you're observing now. "pending" can't become "complete" before it gets to "confirming", so I'm not sure there's a clear understanding about this.

Again, notifications are not clustered the way you're describing. If your transaction moves to the complete state right now, we don't wait x seconds before sending it out.

**Comment by thanksmister** [comment]
Obviously the state changing from pending to complete was just an example, I get how the states work.  I am providing you with the behavior that I currently observe.  

You stated previously that "There is no guarantee about delivering these a single time".   You may not deliberately be clustering them but you also seem to be saying you have no control over that happening.   

My point being that if possible notifications shouldn't be clustered because it just comes across as duplicate data.  Let me ask you this, how long do you wait to transmit a notification after state change, its immediate?    Is there any way to guarantee data isn't clustered together as I observe?

**Comment by g-p-g** [comment]
It's immediate. We also don't use polling.

The thing is: you believe you're getting clustered information. There are lots of assumptions in there, you have to break away from these.

**Comment by thanksmister** [comment]
I understand its not duplicate data. I am just reporting by observation that every 15 seconds the same transactions are sent twice.  If you say that delivery is random and can sometimes be clustered that is acceptable.  

If it can't be controlled then that's an acceptable answer. 

If you are also saying delivery is immediate for state change of a transaction that is all I really care about because that is the expected behavior.

**Comment by g-p-g** [comment]
It's not random, it's not clustered like that. It's immediate for state changes.

Everything can be controlled. Now, I get that it's hard to get a clear view of the details when an internal system controls it. Leaking internal details would hurt you in the sense that you could start creating expectations around them, but like any other internal detail it is subject to change at any moment without notice.

**Comment by thanksmister** [comment]
I only needed to know two things.  Is my observation expected behavior, yes as observed sometimes data comes close together in time (clustered).   Does state change trigger immediate notifications, yes it does.

**Comment by g-p-g** [comment]
Again, it's not clustered. The only reason I'm trying to enforce this fact is that because this is a public space, other people may read this and assume things they shouldn't.

To give you some more information about why you're seeing two notifications close to each other. From time to certain transactions are reprocessed for a variety of reasons. How often and when that happens differs between servers, you mentioned ~10 seconds as that's what playground was roughly configured to (it has since changed to a minute plus other conditions which again, are details). Now, when a BTC -> BTC invoice is reprocessed one notification is sent when that process begins. Another one is sent if no funds have been received yet. So in your case you will receive two because it's an unpaid BTC -> BTC invoice.

**Comment by thanksmister** [comment]
Not to nitpick but what I said was accurate. I stated "sometimes data comes close together in time (clustered)" which is absolutely true observation.   

I think it would have been better to provide your last bit of information first.  We could have just side-stepped the whole "data is clustered" issue because as you say now the data is actually similar but being reported for different reasons (BTC -> BTC invoice).   Let's put this issue to rest as we are only disagreeing over semantics.  

I want to say also that I don't prefer to ask API questions over public space but I was told to do so by Coinapult support and this is the ONLY place to ask API questions.

**Comment by g-p-g** [comment]
There was some misunderstanding over that other channel regarding API questions, but it's ok. Thanks for asking.
